#spring:
#  profiles:
#    include:
#      - common
spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
slack:
  webhook:
    token: ${SLACK_WEBHOOK_TOKEN:}
    url: ${SLACK_WEBHOOK_URL:}
    channel-id: ${SLACK_CHANNEL:}
    username: ${SLACK_USERNAME:default}

oauth:
  kakao:
    base-url: ${KAKAO_BASE_URL}
    client-id: ${KAKAO_CLIENT}
    client-secret: ${KAKAO_SECRET}
    redirect-url: ${KAKAO_REDIRECT}
    app-id: ${KAKAO_APP_ID:default}
    admin-key: ${KAKAO_ADMIN_KEY}

feign:
  kakao:
    info : https://kapi.kakao.com
    oauth : https://kauth.kakao.com
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod
