version: "3.7"

services:
  mariadb:
    image: mariadb:10
    container_name: HIGOODSMaria
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=higoodsLocal
      - MYSQL_ROOT_PASSWORD=admin
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mariadata:/var/lib/maria