object DependencyVersions {
    const val JACKSON_VERSION = "2.10.3"
    const val JWT_VERSION = "0.11.5" // 업그레이드 시 추가 패키지 필요
    const val AWS_VERSION = "2.2.6.RELEASE"
    const val SES_VERSION = "1.11.852"
    const val REDIS_VERSION = "2.7.2"
    const val SERVLET_VERSION = "4.0.1"
    const val UUID_TIME_VERSION = "3.1.4"
    const val SPRING_TRANSACTION = "5.3.22"
    const val QUERYDSL = "5.0.0"
    const val MYSQL = "8.0.28"
    const val APACHE_POI_VERSION = "3.7"
    const val MOCKK_VERSION = "1.13.2"
    const val OPEN_FEIGN_VERSION = "3.1.4"
    const val SENTRY_VERSION = "6.2.1"
    const val ASPECTJ_VERSION = "1.9.7"
    const val FCM_VERSION = "8.1.0"
    const val KOTEST_VERSION = "5.5.4"
    const val KOTEST_EXTENSION_VERSION = "1.1.2"
    const val KOTLIN_LOGGING_VERSION = "3.0.5"
    const val MOCKK_DEFAULT_VERSION = "1.12.4"
    const val MOCKK_SPRING_VERSION = "3.1.2"
    const val REDISSON_VERSION = "3.19.0"
    const val SLACK_API_VERSION = "1.28.0"
    const val REST_DOC_API_SPEC_VERSION = "0.16.4"
    const val SWAGGER_UI_VERSION = "4.11.1"
}