spring:
  profiles:
    include:
      - infra
      - domain
      - common

server:
  servlet:
    context-path: /api
  forward-headers-strategy: framework

springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  swagger-ui:
    tags-sorter: alpha

swagger:
  user: ${SWAGGER_USER:user}
  password: ${SWAGGER_PASSWORD:password}
  version: ${HIGOODS_VERSION:0.0.1-SNAPSHOT}

auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY:testkeytestkeytestkeytestkeytestkeytestkeytestkeytestkeytestkey}
    access-exp: ${JWT_ACCESS_EXP:3600}
    refresh-exp: ${JWT_REFRESH_EXP:3600}
---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod