spring:
  profiles:
    include:
      - infrastructure
      - domain
      - common
---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod