name: Build Api Server
on:
  push:
    tags:
      - Api-v*.*.*
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      image: deploy-test
      tag: latest
    strategy:
      matrix:
        kotlin-version: [ 1.9.0 ]
        java-version: [ 17 ]
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v3

      - name: Set up Kotlin
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          kotlin-version: ${{ matrix.kotlin-version }}
          distribution: 'adopt'

      - name: Get the version
        id: get_version
        run: |
          RELEASE_VERSION_WITHOUT_V="$(cut -d'v' -f2 <<< ${GITHUB_REF#refs/*/})"
          echo ::set-output name=VERSION::$RELEASE_VERSION_WITHOUT_V 

      - name: Start containers  # test 돌릴때 mariadb, redis 필요
        run: docker-compose up -d

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build :HIGOODS-Api:build --no-daemon

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./HIGOODS-Api
          push: true
          tags: higoods2023/HIGOODS-Api:${{ steps.get_version.outputs.VERSION }}